# Generated by Django 5.0.3 on 2024-04-21 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('Medicine_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Medicine_Name', models.CharField(max_length=50)),
                ('Company_name', models.CharField(max_length=30)),
                ('Company_ID', models.IntegerField(default='null')),
                ('Manufacturing_date', models.DateField(verbose_name='Mfg Date (MM/DD/YYYY)')),
                ('Expiry_date', models.DateField(verbose_name='Exp Date (MM/DD/YYYY)')),
                ('Price', models.FloatField()),
                ('stock', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Sold',
            fields=[
                ('Company_name', models.CharField(max_length=30)),
                ('Medicine_Name', models.CharField(max_length=50)),
                ('Manufacturing_date', models.DateField(verbose_name='Mfg Date (MM/DD/YYYY)')),
                ('Expiry_date', models.DateField(verbose_name='Exp Date (MM/DD/YYYY)')),
                ('Price', models.FloatField()),
                ('Customer_name', models.CharField(max_length=30)),
                ('Phone_number', models.IntegerField()),
                ('Quantity', models.IntegerField()),
                ('Bill_amount', models.FloatField()),
                ('Purchase_date', models.DateField(verbose_name='Purchase Date (MM/DD/YYYY)')),
                ('Purchase_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Person_ID', models.IntegerField(default=0)),
                ('Company_ID', models.IntegerField(default=0)),
                ('Medicine_ID', models.IntegerField(default=0)),
            ],
        ),
    ]
