# Generated by Django 5.0.3 on 2024-04-22 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sold',
            name='Person_ID',
            field=models.IntegerField(),
        ),
    ]
