# Generated by Django 5.0.4 on 2024-04-23 02:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_alter_sold_person_id'),
        ('store', '0003_alter_medicine_medicine_id'),
    ]

    operations = [
    ]
